# This is a workflow to help scalable-vega get started with Actions

name: Run Tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: scalable_vega
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: actions/setup-node@v1
        with:
          node-version: '10'

      - name: Install Postgres Requirements
        run: sudo apt-get install postgresql postgresql-contrib libpq-dev
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Setup Database
        run: psql postgresql://postgres@localhost/scalable_vega < scalable_vega.pgsql
        env:
          PGUSER: postgres
          PGPASSWORD: postgres
          
      - name: Clone Repo and Resolve Yarn Dependencies
        run: |
          yarn
          git clone https://github.com/leibatt/vega-transform-pg.git
          cd vega-transform-pg/
          yarn link
          cd ..
          yarn link vega-transform-pg
          yarn add --dev jest

      - name: Test Database
        run: psql -d postgresql://postgres@localhost/scalable_vega -c 'SELECT * FROM pie_chart;'
        env:
          PGUSER: postgres
          PGPASSWORD: postgres

      - name: Test DuckDB
        run: python server.py server.config.json postgres.config.json &
